[package]
name = "symfetch"
version = "0.0.1"
edition = "2024"
license = "MIT"

[dependencies]
clap = { version = "4.5.35", features = ["cargo"] }
serde = "1.0.219"
serde_derive = "1.0.219"
toml = "0.8.20"

# same as rascii_art
image = "0.24.9"
rascii_art = "0.4.5"
