name: "Rust Build and Tests"

on:
    workflow_dispatch:
    push:
        branches: [main]
        paths:
            - "**.rs"
            - ".github/workflows/ci.yml"
    pull_request:
        branches: [main]
        paths:
            - "**.rs"
            - ".github/workflows/ci.yml"
    release:
        types: [created]
    schedule:
        - cron: "0 0 * * 0"

env:
    CARGO_TERM_COLOR: always

jobs:
    isolation_tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                feature-set:
                    - image
                    - image-to-ascii

        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true

            - name: Build with --features ${{ matrix.feature-set }}
              run: cargo build --no-default-features --features "${{ matrix.feature-set }}"

            - name: Test with --features ${{ matrix.feature-set }}
              run: cargo test --no-default-features --features "${{ matrix.feature-set }}"
